# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_in_play', models.CharField(max_length=45)),
                ('word_to_guess', models.CharField(max_length=45)),
                ('bad_guess_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('played_games', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangmangame.Player'),
        ),
    ]
