# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmangame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='player',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
