# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmangame', '0002_auto_20160707_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
    ]
