# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmangame', '0003_player_games_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='guessed_letters',
            field=models.CharField(default='', max_length=100),
        ),
    ]
