# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmangame', '0004_gamestate_guessed_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='word_to_guess',
            field=models.CharField(default='knighthood', max_length=45),
        ),
    ]
