# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmangame', '0005_auto_20160726_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='guessed_letters_sorted',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='word_to_guess',
            field=models.CharField(default='steed', max_length=45),
        ),
    ]
